
 
use_frameworks!
use_modular_headers!
inhibit_all_warnings!

target 'OpenIMSDKUIKit_Example' do
  pod 'OUICore', :path => '../'
  pod 'OUICoreView', :path => '../'
  pod 'OUIIM', :path => '../'
  pod 'OUICalling', :path => '../'
  pod 'ISEmojiView', :path => '../3rd'
  pod 'InputBarAccessoryView', :path => '../3rd'
  pod 'ZLPhotoBrowser', :path => '../3rd'
  pod 'ZFPlayer', :path => '../3rd'
  pod 'AlamofireNetworkActivityLogger', :path => '../3rd'  
  
  pod 'Localize-Swift', '~> 3.2'
  pod 'RxGesture', '~> 4.0.4'
  pod 'ProgressHUD', :git => 'https://github.com/std-s/ProgressHUD.git'
  pod 'Lantern', :git => 'https://github.com/std-s/Lantern.git'
  pod 'MMBAlertsPickers'
  pod 'SGCodeTextField'
  pod 'JXSegmentedView'
    
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'GTSDK', '2.7.1.0-noidfa'
end

post_install do |installer|
  app_project = Xcodeproj::Project.open('OpenIMSDKUIKit.xcodeproj')
    app_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-D', 'COCOAPODS', '-D', 'ENABLE_CALL'
          ]
        end
    end
  app_project.save
  
 installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
#          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
          config.build_settings['ENABLE_BITCODE'] = 'NO'
          config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
          config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
          config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
                
          if target.name == 'OUIIM'
            config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)',
            '-D', 'COCOAPODS',
            '-D', 'ENABLE_CALL',
            ]
          end
          
          if target.name == 'OUICore'
            config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)',
            '-D', 'COCOAPODS',
            ]
          end

          if target.name == 'OUICoreView'
            config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)',
            '-D', 'COCOAPODS',
            ]
          end
    end
  end
end
