
use_frameworks!
use_modular_headers!
inhibit_all_warnings!

target 'OpenIMSDKUIKit_Example' do
  pod 'OUICore', :path => '../'
  pod 'OUICoreView', :path => '../'
  pod 'OUIIM', :path => '../'
  pod 'OUICalling', :path => '../'
  pod 'OpenIMSDK', :path => '../../Open-IM-SDK-iOS/'
  pod 'LiveKitClient', :git => 'https://github.com/livekit/client-sdk-swift.git', :tag => '2.0.10'
  
  pod 'Localize-Swift', '~> 3.2'
  pod 'RxGesture', '~> 4.0.4'
  pod 'ProgressHUD'
  pod 'MMBAlertsPickers'
  pod 'SGCodeTextField'
#  pod 'GTSDK', '2.7.1.0-noidfa'
end

post_install do |installer|

 installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
          config.build_settings['ENABLE_BITCODE'] = 'NO'
          config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
          config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
          config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
          
          if target.name == 'OUIIM'
            config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)',
            '-D', 'COCOAPODS',
            '-D', 'ENABLE_CALL',
            ]
          end
    end
  end
end
